[package]
name = "worldql_messages"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
bytes = { version = "1.1.0", features = ["serde"] }
paste = "1.0.6"
serde = { version = "1.0.133", features = ["derive"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
