// Automatically generated by the Flatbuffers compiler. Do not modify.
pub mod worldql_fb {
  use super::*;
  pub mod messages {
    use super::*;
    mod vec_3d_generated;
    pub use self::vec_3d_generated::*;
    mod record_generated;
    pub use self::record_generated::*;
    mod entity_generated;
    pub use self::entity_generated::*;
    mod message_generated;
    pub use self::message_generated::*;
  } // messages
} // worldql_fb
